server:
  port: 8080
  servlet:
    context-path: /abc
spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp
  # 注册数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.93.35.117:3306/demo?useUnicode=true&characterEncoding=utf8
    username: root
    password: owV19zPHiF?(1
mybatis:
  # 注册映射文件
  mapper-locations: classpath:com/abc/mapper/*.xml
  # 注册实体类别名
  type-aliases-package: com.abc.bean

