server:
  port: 8080
  servlet:
    context-path: /abc
spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp

  # 注册数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.93.35.117:3306/demo?useUnicode=true&characterEncoding=utf8
    username: root
    password: owV19zPHiF?(1
  #连接单机Redis
  redis:
    host: 47.93.35.117
    port: 6379
    password:
  #连接集群Redis
    #sentinel:
      #master: mymaster
      #nodes: sentinel1:6379,sentinel2:6379,sentinel3:6379
  cache:
    #指定当前应用使用的缓存类型
    type: redis
    #指定当前应用所使用的缓存区域名称
    cache-names: realTimeCache

mybatis:
  # 注册映射文件
  mapper-locations: classpath:com/abc/mapper/*.xml
  # 注册实体类别名
  type-aliases-package: com.abc.bean

