server:
  port: 8080
  servlet:
    context-path: /abc
spring:
  profiles:
    active: pro
---
server:
  port: 8081
  servlet:
    context-path: /abc1
spring:
  profiles: dev
---
server:
  port: 8082
  servlet:
    context-path: /abc2
spring:
  profiles: pro
